- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    version: "{{ fzf_version }}"
    dest: ~/.fzf
    depth: 1

- name: Install fzf
  shell: ~/.fzf/install --completion --no-update-rc --key-bindings
