- name: Add Ansible to zsh path
  lineinfile:
          path: ~/.zshrc
          line: 'PATH="$PATH:/home/{{ session_user }}/.local/bin"'
          state: present
          backup: yes

- name: Add Homebrew to zsh path
  lineinfile:
          path: ~/.zshrc
          line: 'PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"'
          state: present
          backup: yes
