- name: Install curl
  become: true
  apt:
      name: curl
      state: latest

- name: Create .config dir
  file:
      dest: ~/.config/nvim
      state: directory
      recurse: true

- name: Copy config files
  copy:
      src: files/
      dest: ~/.config/nvim

- block:
  - name: Require FUSE
    become: true
    apt:
      name: fuse
      state: latest

  - name: Download neovim package
    become: true
    get_url:

      url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage"
      dest: /usr/sbin/nvim
      mode: +x
  when: ansible_os_family == "Debian"
